---
product_name: IntelliJ Platform SDK
product_version:
product_type: DevGuide

url: http://www.jetbrains.org
baseurl: /intellij/sdk/docs/

description: Documentation for working with and extending the IntelliJ Platform SDK

# This is tag 191.6183 (2019.1)
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: 4f9b5f89b2a19ce700b1373a465c16b28ed8ad52

github_repo: JetBrains/intellij-sdk-docs
youtrack_project: IJSDK
