---
product_name: IntelliJ Platform SDK
product_version:
product_type: DevGuide

url: https://www.jetbrains.org
baseurl: /intellij/sdk/docs/

description: Documentation for working with and extending the IntelliJ Platform SDK

# This is tag 193.6494 (2019.3.3)
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: e2d423f42b53eafd5c625b93149a0ebc7e49756c

github_repo: JetBrains/intellij-sdk-docs
youtrack_project: IJSDK

exclude:
  - code_samples
