name: Docs
on:
  push:
    paths-ignore: ['code_samples/**']
  pull_request:
    paths-ignore: ['code_samples/**']

jobs:
 
  documentedProblemsPageVerification:
    name: Documented Problems Page Verification
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Get Plugin Verifier Version
        id: get-version
        run: |
          URL="https://packages.jetbrains.team/maven/p/intellij-plugin-verifier/intellij-plugin-verifier/org/jetbrains/intellij/plugins/verifier-cli/maven-metadata.xml"
          echo "::set-output name=version::$(curl -Ss $URL -L | xpath -q -e "metadata/versioning/latest/text()")
        shell: bash
      - name: Setup Cache
        id: cache
        uses: actions/cache@v2.1.5
        with:
          path: ~/.verifier
          key: ${{ runner.os }}-verifier-${{ steps.get-version.outputs.version }}
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Download Plugin Verifier
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
        run: |
          mkdir -p ~/.verifier/
          curl -L --output ~/.verifier/verifier-all.jar https://packages.jetbrains.team/maven/p/intellij-plugin-verifier/intellij-plugin-verifier/org/jetbrains/intellij/plugins/verifier-cli/$VERSION/verifier-cli-$VERSION-all.jar
      - name: Run Plugin Verifier
        run: |
          PR_REPOSITORY=$(jq -re ".pull_request.head.repo.full_name // empty" $GITHUB_EVENT_PATH) || true
          REPOSITORY=${PR_REPOSITORY:-$GITHUB_REPOSITORY}
          REF=${GITHUB_HEAD_REF:-$GITHUB_REF}
          java -cp ~/.verifier/verifier-all.jar com.jetbrains.pluginverifier.filtering.documented.DocumentedProblemsPageVerifierMain $REPOSITORY ${REF##*/}
